### ISSUE TITLE
pruning weights by L1 regularization

### ISSUE THREAD

**Issue by optyang** [he-y/Awesome-Pruning#12]
Hi,

I would like to bring to your attention our paper on weight pruning accepted by ICLR 2020.

paper url: https://openreview.net/forum?id=HygpthEtvr
code url: https://github.com/optyang/proxsgd

Thank you for considering to include it into the database!

Best,

Yang

**Comment by he-y** [comment]
Thanks. The paper is added.

**Comment by optyang** [comment]
Hi, we have implementations in both TF and pytorch. Thanks!

**Comment by he-y** [comment]
Updated. 
Thanks for your correction.
