### ISSUE TITLE
add new paper

### ISSUE THREAD

**Issue by lmbxmu** [he-y/Awesome-Pruning#13]
Hello, please kindly introduce our one new paper:

Channel Pruning via Automatic Structure Search (IJCAI'2020). 
Link: https://arxiv.org/abs/2001.08565
Code: https://github.com/lmbxmu/ABCPruner

Besides, our previous work, i.e., HRank: Filter Pruning using High-Rank Feature Map (CVPR'2020), has been accepted as Oral Paper.

Thanks.

**Comment by he-y** [comment]
@lmbxmu 
Thanks.
The paper and the "oral" marker are added.
