### ISSUE TITLE
Add paper - ECCV 2020 Oral EagleEye

### ISSUE THREAD

**Issue by bezorro** [he-y/Awesome-Pruning#17]
Hi,

I would like to introduce our simple and fast filter pruning work accepted by ECCV 2020 Oral.

paper url: https://arxiv.org/abs/2007.02491
code url: https://github.com/anonymous47823493/EagleEye

Best,

Bailin Li

**Comment by he-y** [comment]
Thanks for your great work!
I will update all the related papers in ECCV'20 Venue when the proceeding is released.
