### ISSUE TITLE
Add an IJCAI2019 paper

### ISSUE THREAD

**Issue by cheerss** [he-y/Awesome-Pruning#19]
Just a kind remind of filter-level pruning method:
[COP: Customized Deep Model Compression via Regularized Correlation-Based
Filter-Level Pruning](https://www.ijcai.org/Proceedings/2019/0525.pdf)
and [code](https://github.com/ZJULearning/COP)

**Comment by he-y** [comment]
Thanks for the information. The paper is added via [this commit](https://github.com/he-y/Awesome-Pruning/commit/6cc591e55cc87b11a9f6b80ed9ae1fcd6732df77)
