### ISSUE TITLE
The code of SCOP (NeurIPS 2020) has been released.

### ISSUE THREAD

**Issue by yehuitang** [he-y/Awesome-Pruning#24]
Hi Yang,

Thanks for the awesome paper list for network pruning!  Here are our papers and codes about pruning.

The code of NeurIPS 2020 paper 'SCOP: Scientific Control for Reliable Neural Network Pruning' has been released and the link is  
https://github.com/huawei-noah/Pruning/tree/master/SCOP_NeurIPS2020.  The code is written with Pytorch.

What's more, another paper on AAAI 2020, Reborn filters: Pruning convolutional neural networks with limited data, proposes a filter pruning method to reduce the computation cost. The paper link is https://ojs.aaai.org/index.php/AAAI/article/view/6058

Thanks!

**Comment by he-y** [comment]
The link and paper are added. 
Thanks for your good papers.
