### ISSUE TITLE
Sparse Networks from Scratch via Bregman Iterations

### ISSUE THREAD

**Issue by TimRoith** [he-y/Awesome-Pruning#26]
Hi, 

we have a new paper on training sparse networks from scratch via regularization and Bregman Iterations.

Paper url: https://arxiv.org/abs/2105.04319
GitHub: https://github.com/TimRoith/BregmanLearning

Since it is currently under review for a journal I want to ask if you even consider non-conference paper for this 
repository. If not please ignore this issue.

Best,

Tim

**Comment by huanyuhello** [comment]
Thanks
