### ISSUE TITLE
A new pruning paper in ICML2021

### ISSUE THREAD

**Issue by cheerss** [he-y/Awesome-Pruning#27]
Thanks for your great project that helps us meet many valuable pruning papers.

The issue is a kindly remind of the new pruning paper published on ICML 2021: [Accelerate CNNs from Three Dimensions: A Comprehensive Pruning Framework](http://proceedings.mlr.press/v139/wang21e.html).

Thanks again.

**Comment by he-y** [comment]
Thank you for the comment. ICML 2021 venue has been added.
