### ISSUE TITLE
Only Train Once: A One-Shot Neural Network Training And Pruning Framework

### ISSUE THREAD

**Issue by tianyic** [he-y/Awesome-Pruning#29]
Conf: NeurIPS 2021
Paper: Only Train Once: A One-Shot Neural Network Training And Pruning Framework
Code: https://github.com/tianyic/only_train_once
Type: 'F'

**Comment by he-y** [comment]
Fixed. Thanks.

**Comment by cyfwry** [comment]
您好，您发给我的邮件已收到！
