### ISSUE TITLE
Add code and workshop links for implicit filter level sparsity

### ISSUE THREAD

**Issue by mehtadushy** [he-y/Awesome-Pruning#5]
Hi Yang
Thanks for maintaining this list.
The CVPR 2019 paper 'On Implicit Filter Level Sparsity in Convolutional Neural Networks' also has 2 workshop versions, with a few additional results.
Implicit Filter Sparsification In Convolutional Neural Networks (https://arxiv.org/abs/1905.04967), ODML-CDNNR Workshop, ICML 2019
Emergence of Implicit Filter Sparsity in Convolutional Neural Networks (https://openreview.net/forum?id=rylVvNS3hE), Deep Phenomena Workshop, ICML 2019

Also, an example of using the implicit sparsity for speedup is available in the following repository
https://github.com/mehtadushy/SelecSLS-Pytorch as part of the model (https://github.com/mehtadushy/SelecSLS-Pytorch/blob/master/models/selecsls.py#L280)

I would appreciate if you could update the list to include these!

**Comment by he-y** [comment]
Hi, thanks for the information.
I have updated the list.
